version: '3'

tasks:
  ##############################
  ### TESTS
  ##############################
  test:
    cmds:
      - uv run pytest {{.CLI_ARGS}}
    desc: Run pytest
    aliases: [t]
  test:watch:
    cmds:
      # ptw crashes without this fix, ] must be indented
      - sed -i '' 's/^]$/    ]/' pyproject.toml
      - uv run ptw -- {{.CLI_ARGS}}
    desc: Run pytest-watch
    aliases: [tw]
  test:coverage:
    cmds:
      - uv run pytest {{.CLI_ARGS}} --cov --cov-report=lcov:lcov.info --cov-report=term:skip-covered
    desc: Run pytest with coverage reporting
    aliases: [tc]
  test:watch-coverage:
    cmds:
      # ptw crashes without this fix, ] must be indented
      - sed -i '' 's/^]$/    ]/' pyproject.toml
      - uv run ptw -- {{.CLI_ARGS}} --cov --cov-report=lcov:lcov.info --cov-report=term:skip-covered
    desc: Run pytest-watch with coverage reporting
    aliases: [twc, tcw]
  ##############################
  ### LINT
  ##############################
  lint:
    cmds:
      - bash -c "$(curl -fsSL https://gist.githubusercontent.com/Elijas/ce4480d070d4726fe7eb1863d1afd58d/raw/657b0bfea2b660ee3b0938c79f53418a03229cf3/init_generator.sh)"
      - uv run ruff check --fix
    desc: Run Ruff linter in watch mode with auto-fix
    aliases: [l]
  lint-watch:
    cmds:
      - uv run ruff check --fix --watch
    desc: Run Ruff linter in watch mode with auto-fix
    aliases: [lw]
  ##############################
  ### PUBLISH
  ##############################
  bump:patch:
    cmds:
      - uv run pytest -q
      - devtools/generate_project_readme.py `bump-my-version show --increment patch new_version`
      - git add README.md 
      - task lint
      - uv run bump-my-version bump patch
    desc: Bump version [Usage] task bp -- -m "bump version"
    aliases: [bp]
  bump:minor:
    cmds:
      - uv run pytest -q
      - devtools/generate_project_readme.py `bump-my-version show --increment minor new_version`
      - git add README.md 
      - task lint
      - uv run bump-my-version bump minor
    desc: Bump version [Usage] task bm -- -m "bump version"
    aliases: [bm]