version: '3'

tasks:
  ##############################
  ### TESTS
  ##############################
  test:
    cmds:
      - uv run pytest {{.CLI_ARGS}}
    desc: Run pytest
    aliases: [t]
  test:watch:
    cmds:
      # ptw crashes without this fix, ] must be indented
      - sed -i '' 's/^]$/    ]/' pyproject.toml
      - uv run ptw -- {{.CLI_ARGS}}
    desc: Run pytest-watch
    aliases: [tw]
  test:coverage:
    cmds:
      - uv run pytest {{.CLI_ARGS}} --cov --cov-report=lcov:lcov.info --cov-report=term:skip-covered
    desc: Run pytest with coverage reporting
    aliases: [tc]
  test:watch-coverage:
    cmds:
      # ptw crashes without this fix, ] must be indented
      - sed -i '' 's/^]$/    ]/' pyproject.toml
      - uv run ptw -- {{.CLI_ARGS}} --cov --cov-report=lcov:lcov.info --cov-report=term:skip-covered
    desc: Run pytest-watch with coverage reporting
    aliases: [twc, tcw]
  ##############################
  ### LINT
  ##############################
  lint:
    cmds:
      - bash -c "$(curl -fsSL https://gist.githubusercontent.com/Elijas/ce4480d070d4726fe7eb1863d1afd58d/raw/657b0bfea2b660ee3b0938c79f53418a03229cf3/init_generator.sh)"
      - uv run ruff check --fix
    desc: Run Ruff linter in watch mode with auto-fix
    aliases: [l]
  lint-watch:
    cmds:
      - uv run ruff check --fix --watch
    desc: Run Ruff linter in watch mode with auto-fix
    aliases: [lw]
  ##############################
  ### PUBLISH
  ##############################
  ensure-clean-working-tree: # Ensure no changes in the working tree or index, abort if any.
    silent: true
    internal: true
    cmds:
      - if git diff --exit-code > /dev/null 2>&1 && git diff --cached --exit-code > /dev/null 2>&1; then :; else echo "Changes detected in the working tree or index. Please commit or stash them before proceeding."; exit 1; fi
  bump:
    internal: true
    vars:
      type: '{{.CLI_ARGS | default "patch"}}'
    cmds:
      - task: ensure-clean-working-tree
      - uv run pytest -q
      - devtools/generate_project_readme.py `bump-my-version show --increment {{.type}} new_version`
      - git add README.md 
      - task lint
      - uv run bump-my-version bump {{.type}}
    desc: Base bump task (internal)

  bump:patch:
    cmds:
      - task: bump
        vars:
          type: patch
    desc: Bump patch version [Usage] task bp -- -m "bump version"
    aliases: [bp]

  bump:minor:
    cmds:
      - task: bump
        vars:
          type: minor
    desc: Bump minor version [Usage] task bm -- -m "bump version"
    aliases: [bm]