version: '3'

tasks:
  ##############################
  ### TESTS
  ##############################
  test:
    cmds:
      - uv run pytest {{.CLI_ARGS}}
    desc: Run pytest
    aliases: [t]
  test:watch:
    cmds:
      # ptw crashes without this fix, ] must be indented
      - sed -i '' 's/^]$/    ]/' pyproject.toml
      - uv run ptw -- {{.CLI_ARGS}}
    desc: Run pytest-watch
    aliases: [tw]
  test:coverage:
    cmds:
      - uv run pytest {{.CLI_ARGS}} --cov --cov-report=lcov:lcov.info --cov-report=term:skip-covered
    desc: Run pytest with coverage reporting
    aliases: [tc]
  test:watch-coverage:
    cmds:
      # ptw crashes without this fix, ] must be indented
      - sed -i '' 's/^]$/    ]/' pyproject.toml
      - uv run ptw -- {{.CLI_ARGS}} --cov --cov-report=lcov:lcov.info --cov-report=term:skip-covered
    desc: Run pytest-watch with coverage reporting
    aliases: [twc, tcw]
  ##############################
  ### LINT
  ##############################
  lint:
    cmds:
      - bash -c "$(curl -fsSL https://gist.githubusercontent.com/Elijas/ce4480d070d4726fe7eb1863d1afd58d/raw/657b0bfea2b660ee3b0938c79f53418a03229cf3/init_generator.sh)"
      - uv run ruff check --fix
    desc: Run Ruff linter in watch mode with auto-fix
    aliases: [l]
  lint-watch:
    cmds:
      - uv run ruff check --fix --watch
    desc: Run Ruff linter in watch mode with auto-fix
    aliases: [lw]
  ##############################
  ### DOCS
  ##############################
  docs:
    cmds:
      - devtools/generate_project_readme.py
      - git add README.md
    desc: Generate project README
    aliases: [d]
  ##############################
  ### DOCS
  ##############################
  publish:
    cmds:
      - uv run pytest -q
      - task lint docs
      - uv run bump-my-version bump {{.CLI_ARGS}}
    desc: Bump version and publish to PyPI. [Usage] task p -- minor -m "bump version"
    aliases: [p]